/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembayaranspp;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author TOSHIBA DC
 */
public class gantipassword extends javax.swing.JInternalFrame {
String nama = login.getU_nama();
    Connection conn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form datamurid
     */private String a,b;
    private int c;
    /**
     * Creates new form datamurid
     */
    public gantipassword() {
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        initComponents();
          userJL.setText(nama);
        jLabel16.setVisible(false);
        confirmBT.setVisible(false);
        tampungJl.setVisible(false);
       visibleBtn(false);
    }
public void tampilUser(String user){
        userJL.setText(user);
    }
private void visibleBtn(boolean a){
        verifikasBt.setVisible(!a);
        changeBT.setVisible(a);
        jLabel5.setVisible(!a);
        jLabel6.setVisible(a);
        jlblKet.setVisible(a);
        jlblKet1.setVisible(a);
    }
 private void gantiPass(){
        try {
            setKoneksi();
            String sql="update pengguna set "+
                "password = "+"'"+passTF.getText()+"' "+
                "where nama = '"+userJL.getText()+"'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Password Berhasil Diubah","Koneksi Sukses",JOptionPane.INFORMATION_MESSAGE);
            conn.close();
            passTF.setText("");
            visibleBtn(false);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Gagal mengubah password");
        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblKet1 = new javax.swing.JLabel();
        jlblKet = new javax.swing.JLabel();
        confirmBT = new javax.swing.JButton();
        verifikasBt = new javax.swing.JButton();
        changeBT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        userJL = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tampungJl = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MURID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GANTI PASSWORD");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1100, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("Masukkan Kembali Password Baru Anda");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Masukkan Password Lama Anda");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Masukkan Password Baru Anda");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jlblKet1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblKet1.setForeground(new java.awt.Color(255, 0, 51));
        jlblKet1.setText("dan tidak boleh lebih dari 10 digit !");
        jPanel3.add(jlblKet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jlblKet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblKet.setForeground(new java.awt.Color(255, 0, 51));
        jlblKet.setText("Panjang karakter password tidak boleh kurang dari 2 digit");
        jPanel3.add(jlblKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        confirmBT.setText("OK");
        confirmBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmBTMouseEntered(evt);
            }
        });
        confirmBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTActionPerformed(evt);
            }
        });
        jPanel3.add(confirmBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, 30));

        verifikasBt.setText("OK");
        verifikasBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verifikasBtMouseEntered(evt);
            }
        });
        verifikasBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifikasBtActionPerformed(evt);
            }
        });
        jPanel3.add(verifikasBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        changeBT.setText("OK");
        changeBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeBTMouseEntered(evt);
            }
        });
        changeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBTActionPerformed(evt);
            }
        });
        jPanel3.add(changeBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Password  :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nama        :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        passTF.setBorder(null);
        jPanel3.add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 350, 10));
        jPanel3.add(userJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 350, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 420, 280));
        jPanel1.add(tampungJl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifikasBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifikasBtActionPerformed
        // TODO add your handling code here:
        try {
            setKoneksi();
            String sql="select * from pengguna where nama = '"+
            userJL.getText()+"' and password = '"+passTF.getText()+"'";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()) {
                passTF.setText("");
                visibleBtn(true);
            }
            else  {
                passTF.setText("");
                JOptionPane.showMessageDialog(null, "Password lama yang anda masukkan salah!");
                visibleBtn(false);
                passTF.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal");
        }
    
    }//GEN-LAST:event_verifikasBtActionPerformed

    private void changeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBTActionPerformed
        // TODO add your handling code here:
        if(passTF.getText().length()<2) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kurang dari 2 digit !");
            passTF.setText("");
            visibleBtn(true);
            passTF.requestFocus();
        }
        else if(passTF.getText().length()>10) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh lebih dari 10 digit !");
            passTF.setText("");
            visibleBtn(true);
            passTF.requestFocus();
        }
        else {
            b = passTF.getText();
            a = b;
            tampungJl.setText(a);
            passTF.setText("");
            jLabel16.setVisible(true);
            confirmBT.setVisible(true);

            visibleBtn(false);
            verifikasBt.setVisible(false);
            jLabel5.setVisible(false);

        }
    }//GEN-LAST:event_changeBTActionPerformed

    private void confirmBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTActionPerformed
        // TODO add your handling code here:
         a = tampungJl.getText();
        b = passTF.getText();

        if (a.equals(b)) {
            c = JOptionPane.showConfirmDialog(null, "Anda yakin ingin merubah password?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
            if (c == 0){
                gantiPass();
                jLabel16.setVisible(false);
                confirmBT.setVisible(false);
            }
            else
            {
                visibleBtn(false);
                passTF.setText("");
                jLabel16.setVisible(false);
                confirmBT.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Password baru yang anda masukkan tidak cocok!");
            passTF.setText("");
            passTF.requestFocus();
        }
    }//GEN-LAST:event_confirmBTActionPerformed

    private void verifikasBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verifikasBtMouseEntered
        // TODO add your handling code here:
        verifikasBt.setBackground(new Color(0,153,153));
      verifikasBt.setForeground(Color.red);
    }//GEN-LAST:event_verifikasBtMouseEntered

    private void changeBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBTMouseEntered
        // TODO add your handling code here:
         changeBT.setBackground(new Color(0,153,153));
      changeBT.setForeground(Color.red);
    }//GEN-LAST:event_changeBTMouseEntered

    private void confirmBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBTMouseEntered
        // TODO add your handling code here:
          confirmBT.setBackground(new Color(0,153,153));
      confirmBT.setForeground(Color.red);
    }//GEN-LAST:event_confirmBTMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeBT;
    private javax.swing.JButton confirmBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlblKet;
    private javax.swing.JLabel jlblKet1;
    private javax.swing.JTextField passTF;
    private javax.swing.JLabel tampungJl;
    private javax.swing.JLabel userJL;
    private javax.swing.JButton verifikasBt;
    // End of variables declaration//GEN-END:variables
public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/pembayaranspp","root","");
            st=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
}
